FROM elasticsearch:2.1.2

# Install HEAD plugin
RUN /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head

# Install HEAD plugin
RUN /usr/share/elasticsearch/bin/plugin install elasticsearch/elasticsearch-mapper-attachments/3.1.2

EXPOSE 9200 9300
