version: '2'

services:
  elasticsearch:
    build: elastic
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
  pdfindexer:
    build: indexserver
    ports:
      - "8080:8080"
