version: '2'

services:
  elasticsearch:
    build: ./elastic
    environment:
      - ES_HEAP_SIZE=1g
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elastic/esdata:/usr/share/elasticsearch/data
  pdfindexer:
    build: ./indexserver
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    volumes:
      - ./indexserver/pdf-files:/pdf-files:ro
